platform :ios, '8.0'
#use_frameworks!

target 'PCDottedPasscodeView_Example' do
  pod 'PCDottedPasscodeView', :path => '../'

  target 'PCDottedPasscodeView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
